### ISSUE TITLE
执行npm报错

### ISSUE THREAD

**Issue by chishichao** [Carrotzpc/ant-koa-demo#3]
C:\ant-koa-demo-master>cnpm run dev

> ant-koa-demo@0.1.0 dev C:\ant-koa-demo-master
> node index.js

listening on port 3001

npm ERR! Windows_NT 6.1.7600
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Users\chishichao\AppD
ata\Roaming\npm\node_modules\cnpm\node_modules\npm\bin\npm-cli.js" "--us
erconfig=C:\Users\chishichao\.cnpmrc" "--disturl=https://npm.taobao.org/mirro
rs/node" "--cache=C:\Users\chishichao\.cnpm" "--registry=https://registry.npm
.taobao.org" "--node-gyp=C:\Users\chishichao\AppData\Roaming\npm\node_modu
les\cnpm\node_modules\node-gyp\bin\node-gyp.js" "run" "dev"
npm ERR! node v5.4.1
npm ERR! npm  v2.14.19
npm ERR! code ELIFECYCLE
npm ERR! ant-koa-demo@0.1.0 dev: `node index.js`
npm ERR! Exit status 3221225501
npm ERR!
npm ERR! Failed at the ant-koa-demo@0.1.0 dev script 'node index.js'.
npm ERR! This is most likely a problem with the ant-koa-demo package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node index.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ant-koa-demo
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls ant-koa-demo
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\ant-koa-demo-master\npm-debug.log

**Comment by Carrotzpc** [comment]
第一次执行 `cnpm install`的时候是不是有报错？重新执行`cnpm install`，然后执行`npm run dev`试下

**Comment by chishichao** [comment]
重新执行了cnpm install,但是还是报错。报了好多依赖错误，安装了几个，还是一直报依赖错误？？
module.js:327
    throw err;
    ^

Error: Cannot find module 'humanize-number'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\ant-koa-demo-master\node_modules\koa-logger\index.
js:6:16)
    at Module._compile (module.js:397:26)
    at Object.Module._extensions..js (module.js:404:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
▌ ╢░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░

**Comment by Carrotzpc** [comment]
这种情况要把项目根目录`node_modules`文件夹删除，把 `npm` 升级到3.0以上，执行 `cnpm install`，参考[https://github.com/ant-design/ant-design/issues/650](https://github.com/ant-design/ant-design/issues/650)
